# -*- coding: utf-8 -*-
"""JSON Refiner Advanced Edition

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jFkAp4PRX1PmF4cocg4VzdCG7HZSyTDm
"""

!pip install -U transformers

# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("text-generation", model="ibm-granite/granite-3.3-2b-instruct")
messages = [
    {"role": "user", "content": "Who are you?"},
]

pipe(messages)

# Load model directly
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("ibm-granite/granite-3.3-2b-instruct")
model = AutoModelForCausalLM.from_pretrained("ibm-granite/granite-3.3-2b-instruct")

messages = [
    {"role": "user", "content": "Who are you?"},
]

inputs = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt=True,
    tokenize=True,
    return_dict=True,
    return_tensors="pt",
).to(model.device)

outputs = model.generate(**inputs, max_new_tokens=40)
print(tokenizer.decode(outputs[0][inputs["input_ids"].shape[-1]:]))

!pip install -q gradio json5 jsonschema python-dotenv pydantic
import gradio as gr
import json
import re
import ast
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Any, Tuple, Optional, Set
import json5
from jsonschema import validate, ValidationError, Draft7Validator
from enum import Enum

# ==============================================================================
# JSON REFINER - ADVANCED VERSION WITH PREMIUM FEATURES (FIXED)
# ==============================================================================
class CaseStyle(Enum):
    """Case conversion styles"""
    SNAKE_CASE = "snake_case"
    CAMEL_CASE = "camelCase"
    KEBAB_CASE = "kebab-case"
    PASCAL_CASE = "PascalCase"

# Mapping for Gradio radio button values to CaseStyle enum
CASE_STYLE_MAP = {
    "snake_case": CaseStyle.SNAKE_CASE,
    "camelCase": CaseStyle.CAMEL_CASE,
    "kebab-case": CaseStyle.KEBAB_CASE,
    "PascalCase": CaseStyle.PASCAL_CASE,
}

class JSONRefinerCore:
    """Advanced JSON parsing and refinement engine"""

    def __init__(self):
        self.conversion_log = []
        self.validation_errors = []
        self.transformation_history = []

    @staticmethod
    def to_snake_case(text: str) -> str:
        text = re.sub(r'(?<!^)(?=[A-Z])', '_', text).lower()
        return text.replace('-', '_')

    @staticmethod
    def to_camel_case(text: str) -> str:
        parts = text.split('_')
        return parts[0] + ''.join(word.capitalize() for word in parts[1:])

    @staticmethod
    def to_kebab_case(text: str) -> str:
        text = re.sub(r'(?<!^)(?=[A-Z])', '-', text).lower()
        return text.replace('_', '-')

    @staticmethod
    def to_pascal_case(text: str) -> str:
        return ''.join(word.capitalize() for word in text.replace('-', '_').split('_'))

    @staticmethod
    def normalize_key(key: str, case_style: CaseStyle) -> str:
        if case_style == CaseStyle.SNAKE_CASE:
            return JSONRefinerCore.to_snake_case(key)
        elif case_style == CaseStyle.CAMEL_CASE:
            return JSONRefinerCore.to_camel_case(key)
        elif case_style == CaseStyle.KEBAB_CASE:
            return JSONRefinerCore.to_kebab_case(key)
        elif case_style == CaseStyle.PASCAL_CASE:
            return JSONRefinerCore.to_pascal_case(key)
        return key # Fallback if style not matched

    @staticmethod
    def infer_type(value: str) -> Any:
        """Infer and convert value to correct JSON type"""
        value = value.strip()

        if value.lower() in ['null', 'none', 'nil', 'undefined', 'n/a', 'na']:
            return None

        if value.lower() in ['true', 'yes', 'on', '1']:
            return True
        if value.lower() in ['false', 'no', 'off', '0']:
            return False

        try:
            if '.' not in value:
                return int(value)
        except ValueError:
            pass
        try:
            return float(value)
        except ValueError:
            pass
        # Try parsing as JSON array/object
        if value.startswith('[') and value.endswith(']') or \
           value.startswith('{') and value.endswith('}'):
            try:
                return json.loads(value)
            except json.JSONDecodeError:
                pass
        return value

    @staticmethod
    def _convert_keys_recursive(obj, case_enum: CaseStyle):
        if isinstance(obj, dict):
            return {
                JSONRefinerCore.normalize_key(k, case_enum): JSONRefinerCore._convert_keys_recursive(v, case_enum)
                for k, v in obj.items()
            }
        elif isinstance(obj, list):
            return [JSONRefinerCore._convert_keys_recursive(item, case_enum) for item in obj]
        return obj

    @staticmethod
    def parse_key_value_text(text: str, case_style: CaseStyle = CaseStyle.SNAKE_CASE) -> Tuple[Dict, List[str]]:
        """Parse key-value text into dictionary"""
        result = {}
        errors = []
        # duplicates = [] # Original had this, but it's not used.

        lines = text.split('\n')

        for line_num, line in enumerate(lines, 1):
            line = line.strip()

            if not line or line.startswith('#'):
                continue

            if ':' not in line:
                errors.append(f"Line {line_num}: No colon separator found - '{line}'")
                continue

            try:
                key, value_str = line.split(':', 1)
                key = JSONRefinerCore.normalize_key(key.strip(), case_style)
                value = JSONRefinerCore.infer_type(value_str)
                result[key] = value
            except Exception as e:
                errors.append(f"Line {line_num}: Error parsing '{line}' - {e}")
        return result, errors

    @staticmethod
    def validate_json_schema(data: Dict, schema: Dict) -> Tuple[bool, List[str]]:
        """Validate JSON against schema"""
        errors = []
        try:
            validate(instance=data, schema=schema)
            return True, []
        except ValidationError as e:
            return False, [str(e)]
        except Exception as e:
            return False, [f"Schema validation error: {str(e)}"]

    @staticmethod
    def check_required_fields(data: Dict, required_fields: List[str]) -> Tuple[bool, List[str]]:
        """Check for required fields"""
        errors = []
        missing = []
        for field in required_fields:
            if field not in data:
                missing.append(field)

        if missing:
            return False, [f"Missing required fields: {', '.join(missing)}"]
        return True, []

    @staticmethod
    def flatten_json(data: Dict) -> Dict:
        flattened = {}
        def _flatten(obj, prefix=""):
            if isinstance(obj, dict):
                for k, v in obj.items():
                    _flatten(v, f"{prefix}{k}.")
            elif isinstance(obj, list):
                for i, v in enumerate(obj):
                    _flatten(v, f"{prefix}{i}.")
            else:
                if prefix:
                    flattened[prefix[:-1]] = obj
        _flatten(data)
        return flattened

    @staticmethod
    def unflatten_json(data: Dict) -> Dict:
        unflattened = {}
        for key, value in data.items():
            parts = key.split('.')
            d = unflattened
            for part_idx, part in enumerate(parts[:-1]):
                is_array_index = False
                if part.isdigit():
                    try:
                        idx = int(part)
                        is_array_index = True
                    except ValueError: # Not a valid int, treat as string key
                        pass

                if is_array_index:
                    if not isinstance(d, list):
                        # If current level is dict, it should become a list if an index is encountered
                        if part_idx == 0: # If at root, make unflattened a list
                            unflattened = []
                            d = unflattened
                        else:
                            # This path is problematic if a dict key becomes an array index mid-path
                            # For simplicity, let's assume consistent types for now.
                            # A more robust solution might require more complex type inference or hints.
                            pass
                    while len(d) <= idx:
                        d.append(None) # Fill with None or empty dict/list if needed
                    if d[idx] is None or isinstance(d[idx], dict) and not d[idx]: # If None or empty dict, initialize for next level
                        if part_idx < len(parts) - 2 and parts[part_idx + 1].isdigit(): # Next is an index, prepare a list
                            d[idx] = []
                        else:
                            d[idx] = {}
                    d = d[idx]
                else: # Treat as dictionary key
                    if not isinstance(d, dict):
                        # Similar logic for type inconsistency, assume dict for non-index keys
                        pass
                    if part not in d:
                        if part_idx < len(parts) - 2 and parts[part_idx + 1].isdigit():
                            d[part] = []
                        else:
                            d[part] = {}
                    d = d[part]

            final_key_or_idx = parts[-1]
            if final_key_or_idx.isdigit() and isinstance(d, list):
                idx = int(final_key_or_idx)
                while len(d) <= idx:
                    d.append(None)
                d[idx] = value
            elif isinstance(d, dict):
                d[final_key_or_idx] = value
            else:
                # Handle cases where the path leads to a non-dict/list for final assignment
                pass # This needs more robust error handling or assumption

        return unflattened

    @staticmethod
    def get_json_statistics(data: Any) -> Tuple[int, Set[str], List[str], bool, bool, bool]:
        """Collects statistics about keys, value types, and top-level keys in a JSON object."""
        all_keys = set()
        all_value_types = set()
        top_level_keys = set()
        has_nested_object = False
        has_arrays = False
        has_null_values = False

        def _collect_stats_recursive(obj, current_path=""):
            nonlocal has_nested_object, has_arrays, has_null_values

            if isinstance(obj, dict):
                all_value_types.add("dict")
                if current_path: # If it's not the root object, it's a nested object
                    has_nested_object = True
                for k, v in obj.items():
                    if not current_path: # Only add to top_level_keys if at the root
                        top_level_keys.add(k)
                    full_key = f"{current_path}.{k}" if current_path else k
                    all_keys.add(full_key)
                    _collect_stats_recursive(v, full_key)
            elif isinstance(obj, list):
                all_value_types.add("list")
                has_arrays = True
                for i, item in enumerate(obj):
                    _collect_stats_recursive(item, current_path)
            elif obj is None:
                all_value_types.add("null") # JSON 'null'
                has_null_values = True
            else:
                all_value_types.add(type(obj).__name__)

        _collect_stats_recursive(data)
        return len(all_keys), sorted(list(all_value_types)), sorted(list(top_level_keys)), has_nested_object, has_arrays, has_null_values

# Instantiate refiner for functions that might still expect it if not fully converted to static calls
# Although, direct static calls are preferred.
# refiner = JSONRefinerCore() # Not strictly needed if all calls are static, but kept as a global pattern from original code

# Wrapper functions for Gradio interface
def convert_json_case_wrapper(json_text: str, target_case: str) -> Tuple[str, str]:
    """Convert JSON keys to different case styles"""
    try:
        data = json.loads(json_text)
        case_enum = CASE_STYLE_MAP.get(target_case)
        if not case_enum:
            raise ValueError(f"Invalid case style: {target_case}")
        converted = JSONRefinerCore._convert_keys_recursive(data, case_enum)
        output = json.dumps(converted, indent=2, ensure_ascii=False)
        return output, f"✅ Converted to {target_case}!"
    except Exception as e:
        return "", f"❌ Error: {str(e)}"

def flatten_json_func(json_text: str) -> Tuple[str, str]:
    """Flatten JSON structure"""
    try:
        data = json.loads(json_text)
        flattened = JSONRefinerCore.flatten_json(data)
        output = json.dumps(flattened, indent=2, ensure_ascii=False)
        return output, "✅ JSON flattened!"
    except Exception as e:
        return "", f"❌ Error: {str(e)}"

def unflatten_json_func(json_text: str) -> Tuple[str, str]:
    """Unflatten JSON structure"""
    try:
        data = json.loads(json_text)
        unflattened = JSONRefinerCore.unflatten_json(data)
        output = json.dumps(unflattened, indent=2, ensure_ascii=False)
        return output, "✅ JSON unflattened!"
    except Exception as e:
        return "", f"❌ Error: {str(e)}"

# Placeholder for merge_json_func (implied by Gradio TAB 4)
def merge_json_func(json1_str: str, json2_str: str, json3_str: str = "{}") -> Tuple[str, str]:
    try:
        data1 = json.loads(json1_str or "{}")
        data2 = json.loads(json2_str or "{}")
        data3 = json.loads(json3_str or "{}")
        merged = {**data1, **data2, **data3}
        output = json.dumps(merged, indent=2, ensure_ascii=False)
        return output, "✅ JSON merged!"
    except Exception as e:
        return "", f"❌ Error: {str(e)}"

def get_json_statistics_func(json_text: str) -> Tuple[str, str]:
    """Generates statistics for a given JSON string."""
    try:
        data = json.loads(json_text)
        total_keys, value_types, top_level_keys, has_nested_object, has_arrays, has_null_values = JSONRefinerCore.get_json_statistics(data) # Unpack new return value

        stats_output = f"- **Top-Level Keys**: {', '.join(top_level_keys)}\n"
        stats_output += f"- **Total Keys**: {total_keys}\n"
        stats_output += f"- **Has Nested Object**: {'Yes' if has_nested_object else 'No'}\n"
        stats_output += f"- **Has Arrays**: {'Yes' if has_arrays else 'No'}\n"
        stats_output += f"- **Has Null Values**: {'Yes' if has_null_values else 'No'}\n"
        stats_output += f"- **Value Types**: {', '.join(value_types)}\n"

        return stats_output, "✅ Statistics generated!"
    except json.JSONDecodeError as e:
        return "", f"❌ Error: Invalid JSON input - {e}"
    except Exception as e:
        return "", f"❌ Error generating statistics: {str(e)}"

# Placeholder functions for history tab
def download_history() -> str:
    return "History download not implemented yet."

def clear_history() -> str:
    return "History cleared (not really, function not implemented yet)."

# Gradio interface setup
with gr.Blocks() as demo:
    gr.Markdown("# 💎 JSON Refiner & Validator")

    with gr.Tabs():
        # ============ TAB 1: Core Refining =============
        with gr.TabItem("🔧 Core Refining"):
            with gr.Row():
                with gr.Column(scale=1):
                    gr.Markdown("### 📥 Input Format")
                    text_input = gr.Textbox(
                        label="Key-Value Text",
                        lines=12,
                        value="name: John Doe\nage: 28\nis_active: true\nbalance: 1500.50\nemail: john@example.com\ntags: [\"admin\", \"user\"]"
                    )

                    case_style = gr.Radio(
                        ["snake_case", "camelCase", "kebab-case", "PascalCase"],
                        value="snake_case",
                        label="🎨 Key Case Style"
                    )

                    with gr.Row():
                        remove_nulls = gr.Checkbox(label="Remove Nulls", value=False)
                        flatten_checkbox = gr.Checkbox(label="Flatten", value=False) # Renamed to avoid conflict
                        pretty_print = gr.Checkbox(label="Pretty Print", value=True)

                    refine_btn = gr.Button("✨ Refine JSON", size="lg", variant="primary")

                with gr.Column(scale=1):
                    gr.Markdown("### 📤 Output JSON")
                    output_json = gr.Code(language="json", label="Refined JSON", lines=20)
                    refine_status = gr.Markdown()

            # Define core refining logic (simplified for now)
            def core_refine(text, case, remove_null, flatten_bool, pretty):
                case_enum = CASE_STYLE_MAP.get(case)
                if not case_enum:
                    return json.dumps({"error": "Invalid case style", "details": f"Unknown case: {case}"}, indent=2), f"❌ Errors: Unknown case style {case}"
                data, errors = JSONRefinerCore.parse_key_value_text(text, case_enum)
                if errors:
                    return json.dumps({"error": "Parsing errors", "details": errors}, indent=2), f"❌ Errors: {'; '.join(errors)}"

                if remove_null:
                    data = {k: v for k, v in data.items() if v is not None}

                if flatten_bool:
                    data = JSONRefinerCore.flatten_json(data)

                # Calculate statistics
                total_keys, value_types, top_level_keys, has_nested_object, has_arrays, has_null_values = JSONRefinerCore.get_json_statistics(data) # Unpack new return value
                stats_output = f"- **Top-Level Keys**: {', '.join(top_level_keys)}\n"
                stats_output += f"- **Total Keys**: {total_keys}\n"
                stats_output += f"- **Has Nested Object**: {'Yes' if has_nested_object else 'No'}\n"
                stats_output += f"- **Has Arrays**: {'Yes' if has_arrays else 'No'}\n"
                stats_output += f"- **Has Null Values**: {'Yes' if has_null_values else 'No'}\n"
                stats_output += f"- **Value Types**: {', '.join(value_types)}\n"

                base_status = ""
                if pretty:
                    json_output = json.dumps(data, indent=2, ensure_ascii=False)
                    base_status = "✅ Refined and formatted!"
                else:
                    json_output = json.dumps(data, ensure_ascii=False)
                    base_status = "✅ Refined!"

                # Combine status with statistics
                final_status = f"{base_status}\n\n--- JSON Statistics ---\n{stats_output}"

                return json_output, final_status

            refine_btn.click(
                core_refine,
                inputs=[text_input, case_style, remove_nulls, flatten_checkbox, pretty_print],
                outputs=[output_json, refine_status]
            )

        # ============ TAB 2: Validation =============
        with gr.TabItem("✅ Validation"):
            gr.Markdown("### 🔍 Validate JSON Structure")

            with gr.Row():
                with gr.Column(scale=1):
                    json_to_validate = gr.Code(
                        language="json",
                        label="JSON to Validate",
                        lines=10,
                        value='{"name": "John", "age": 28}'
                    )

                    required_fields_input = gr.Textbox(
                        label="Required Fields (comma-separated)",
                        value="name, age, email"
                    )
                    validate_btn = gr.Button("🚀 Validate JSON", size="lg", variant="primary")

                with gr.Column(scale=1):
                    schema_input = gr.Code(
                        language="json",
                        label="JSON Schema (Optional)",
                        lines=10,
                        value='{"type": "object", "properties": {"name": {"type": "string"}, "age": {"type": "integer"}}, "required": ["name"]}'
                    )
                    validation_output = gr.Textbox(label="Validation Result", lines=5)
                    validation_status = gr.Markdown()

            def validate_json_wrapper(json_str, required_fields_str, schema_str):
                try:
                    data = json.loads(json_str)
                except json.JSONDecodeError as e:
                    return f"Invalid JSON: {e}", "❌ Invalid JSON!"

                required_fields = [f.strip() for f in required_fields_str.split(',') if f.strip()]

                is_valid_fields, field_errors = JSONRefinerCore.check_required_fields(data, required_fields)

                schema_errors = []
                if schema_str:
                    try:
                        schema = json.loads(schema_str)
                        is_valid_schema, schema_errors = JSONRefinerCore.validate_json_schema(data, schema)
                        if not is_valid_schema:
                            return "\n".join(schema_errors), "❌ Schema validation failed!"
                    except json.JSONDecodeError as e:
                        return f"Invalid Schema JSON: {e}", "❌ Invalid Schema!"

                if not is_valid_fields:
                    return "\n".join(field_errors), "❌ Missing required fields!"

                return "JSON is valid!", "✅ Validation successful!"

            validate_btn.click(
                validate_json_wrapper,
                inputs=[json_to_validate, required_fields_input, schema_input],
                outputs=[validation_output, validation_status]
            )

        # ============ TAB 3: Case Conversion =============
        with gr.TabItem("🎨 Case Conversion"):
            gr.Markdown("### 🔄 Convert JSON Key Cases")

            with gr.Row():
                with gr.Column(scale=1):
                    json_for_case = gr.Code(
                        language="json",
                        label="Input JSON",
                        lines=10,
                        value='{"firstName": "John", "lastName": "Doe"}'
                    )

                    target_case = gr.Radio(
                        ["snake_case", "camelCase", "kebab-case", "PascalCase"],
                        value="camelCase",
                        label="Target Case Style"
                    )

                    case_convert_btn = gr.Button("🔄 Convert", size="lg", variant="primary")

                with gr.Column(scale=1):
                    case_converted_output = gr.Code(language="json", label="Converted JSON", lines=10)
                    case_conversion_status = gr.Markdown()

            case_convert_btn.click(
                convert_json_case_wrapper,
                inputs=[json_for_case, target_case],
                outputs=[case_converted_output, case_conversion_status]
            )

        # ============ TAB 4: Merging =============
        with gr.TabItem("🔗 Merge JSON"):
            gr.Markdown("### 🔀 Merge Multiple JSON Objects")

            with gr.Row():
                with gr.Column(scale=1):
                    json1 = gr.Code(
                        language="json",
                        label="JSON #1",
                        lines=8,
                        value='{"name": "John"}'
                    )

                    json2 = gr.Code(
                        language="json",
                        label="JSON #2",
                        lines=8,
                        value='{"age": 28}'
                    )

                    json3 = gr.Code(
                        language="json",
                        label="JSON #3 (optional)",
                        lines=8,
                        value='{"city": "New York"}'
                    )
                    merge_btn = gr.Button("➕ Merge JSONs", size="lg", variant="primary")

                with gr.Column(scale=1):
                    merged_json_output = gr.Code(language="json", label="Merged JSON", lines=20)
                    merge_status = gr.Markdown()

            merge_btn.click(
                merge_json_func,
                inputs=[json1, json2, json3],
                outputs=[merged_json_output, merge_status]
            )

        # ============ TAB 5: Flattening =============
        with gr.TabItem("📦 Flatten/Unflatten"):
            with gr.Tabs():
                with gr.TabItem("Flatten"):
                    gr.Markdown("### 📦 Flatten Nested JSON")

                    with gr.Row():
                        flatten_input = gr.Code(
                            language="json",
                            label="Nested JSON",
                            lines=10,
                            value='{"user": {"name": "John", "age": 28}}'
                        )
                        flatten_btn = gr.Button("Flatten", size="lg", variant="primary")

                    flatten_out = gr.Code(
                        language="json",
                        label="Flattened JSON",
                        lines=10
                    )

                    flatten_status = gr.Markdown()

                    flatten_btn.click(
                        flatten_json_func,
                        inputs=[flatten_input],
                        outputs=[flatten_out, flatten_status]
                    )

                with gr.TabItem("Unflatten"):
                    gr.Markdown("### ↩️ Unflatten JSON")

                    with gr.Row():
                        unflatten_input = gr.Code(
                            language="json",
                            label="Flattened JSON",
                            lines=10,
                            value='{"user.name": "John", "user.age": 28}'
                        )
                        unflatten_btn = gr.Button("Unflatten", size="lg", variant="primary")

                    unflatten_out = gr.Code(
                        language="json",
                        label="Unflattened JSON",
                        lines=10
                    )

                    unflatten_status = gr.Markdown()

                    unflatten_btn.click(
                        unflatten_json_func,
                        inputs=[unflatten_input],
                        outputs=[unflatten_out, unflatten_status]
                    )

        # ============ TAB 6: History =============
        with gr.TabItem("📜 History"):
            gr.Markdown("### 📊 Transformation History")

            with gr.Row():
                history_btn = gr.Button("⬇️ Download History", size="lg", variant="secondary")
                clear_history_btn = gr.Button("🗑️ Clear History", size="lg", variant="stop")

            history_output = gr.Textbox(
                label="History Report",
                lines=15
            )

            history_status = gr.Markdown()

            history_btn.click(
                download_history,
                outputs=[history_output]
            )

            clear_history_btn.click(
                clear_history,
                outputs=[history_status]
            )

        # ============ TAB 7: Guide =============
        with gr.TabItem("📘 Guide"):
            gr.Markdown("""
# 📘 JSON Refiner - Complete Guide\n\n## Input Format\nUse simple **Key: Value** format:\nname: John Doe\nage: 28\nis_active: true\nbalance: 1500.50\n\n## Type Inference\n**Automatic type detection:**\n- `true`, `false`, `yes`, `no` → Boolean\n- `null`, `none`, `undefined` → Null\n- `123`, `456` → Integer\n- `3.14`, `2.5` → Float\n- `[1, 2, 3]` → Array (if valid JSON)\n- `{\"key\": \"value\"}` → Object (if valid JSON)\n""")

        # ============ TAB 8: Statistics =============
        with gr.TabItem("📊 Statistics"):
            gr.Markdown("### 📈 JSON Statistics")

            with gr.Row():
                with gr.Column(scale=1):
                    json_for_stats = gr.Code(
                        language="json",
                        label="Input JSON for Statistics",
                        lines=10,
                        value='{"name": "John Doe", "age": 28, "details": {"active": true, "tags": ["user", "admin"]}, "balance": 1500.50}'
                    )
                    stats_btn = gr.Button("📊 Get Statistics", size="lg", variant="primary")

                with gr.Column(scale=1):
                    stats_output = gr.Textbox(
                        label="JSON Statistics",
                        lines=10
                    )
                    stats_status = gr.Markdown()

            stats_btn.click(
                get_json_statistics_func,
                inputs=[json_for_stats],
                outputs=[stats_output, stats_status]
            )

print("\n JSON Refiner Advanced Ready!")
demo.launch(share=True,show_error=True,show_api=False)